// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: block.proto

package blockdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Corresponds to bertha_types::Block
type Block struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParentHash            []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	OmmersHash            []byte                 `protobuf:"bytes,2,opt,name=ommers_hash,json=ommersHash,proto3" json:"ommers_hash,omitempty"`
	Beneficiary           []byte                 `protobuf:"bytes,3,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	StateRoot             []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Difficulty            uint64                 `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number                uint64                 `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit              uint64                 `protobuf:"varint,7,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Timestamp             uint64                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData             []byte                 `protobuf:"bytes,9,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	PrevRandao            []byte                 `protobuf:"bytes,10,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	Nonce                 []byte                 `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Transactions          []*Transaction         `protobuf:"bytes,12,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Receipts              []*TransactionReceipt  `protobuf:"bytes,13,rep,name=receipts,proto3" json:"receipts,omitempty"`
	BaseFeePerGas         []byte                 `protobuf:"bytes,14,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,oneof" json:"base_fee_per_gas,omitempty"`
	WithdrawalsRoot       []byte                 `protobuf:"bytes,15,opt,name=withdrawals_root,json=withdrawalsRoot,proto3,oneof" json:"withdrawals_root,omitempty"`
	BlobGasUsed           *uint64                `protobuf:"varint,16,opt,name=blob_gas_used,json=blobGasUsed,proto3,oneof" json:"blob_gas_used,omitempty"`
	ExcessBlobGas         *uint64                `protobuf:"varint,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3,oneof" json:"excess_blob_gas,omitempty"`
	ParentBeaconBlockRoot []byte                 `protobuf:"bytes,18,opt,name=parent_beacon_block_root,json=parentBeaconBlockRoot,proto3,oneof" json:"parent_beacon_block_root,omitempty"`
	RequestsHash          []byte                 `protobuf:"bytes,19,opt,name=requests_hash,json=requestsHash,proto3,oneof" json:"requests_hash,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Block) GetOmmersHash() []byte {
	if x != nil {
		return x.OmmersHash
	}
	return nil
}

func (x *Block) GetBeneficiary() []byte {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

func (x *Block) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *Block) GetDifficulty() uint64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Block) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Block) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Block) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *Block) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *Block) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetReceipts() []*TransactionReceipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

func (x *Block) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *Block) GetWithdrawalsRoot() []byte {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

func (x *Block) GetBlobGasUsed() uint64 {
	if x != nil && x.BlobGasUsed != nil {
		return *x.BlobGasUsed
	}
	return 0
}

func (x *Block) GetExcessBlobGas() uint64 {
	if x != nil && x.ExcessBlobGas != nil {
		return *x.ExcessBlobGas
	}
	return 0
}

func (x *Block) GetParentBeaconBlockRoot() []byte {
	if x != nil {
		return x.ParentBeaconBlockRoot
	}
	return nil
}

func (x *Block) GetRequestsHash() []byte {
	if x != nil {
		return x.RequestsHash
	}
	return nil
}

// Corresponds to bertha_types::Transaction
type Transaction struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	TransactionType      uint64                  `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	ChainId              []byte                  `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce                uint64                  `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice             []byte                  `protobuf:"bytes,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit             uint64                  `protobuf:"varint,5,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	To                   []byte                  `protobuf:"bytes,6,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Value                []byte                  `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	Data                 []byte                  `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	AccessList           []*AccessListEntry      `protobuf:"bytes,9,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	MaxFeePerGas         []byte                  `protobuf:"bytes,10,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas []byte                  `protobuf:"bytes,11,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	BlobVersionedHashes  [][]byte                `protobuf:"bytes,12,rep,name=blob_versioned_hashes,json=blobVersionedHashes,proto3" json:"blob_versioned_hashes,omitempty"`
	MaxFeePerBlobGas     []byte                  `protobuf:"bytes,13,opt,name=max_fee_per_blob_gas,json=maxFeePerBlobGas,proto3" json:"max_fee_per_blob_gas,omitempty"`
	AuthorizationList    []*SetCodeAuthorization `protobuf:"bytes,14,rep,name=authorization_list,json=authorizationList,proto3" json:"authorization_list,omitempty"`
	YParity              []byte                  `protobuf:"bytes,15,opt,name=y_parity,json=yParity,proto3" json:"y_parity,omitempty"`
	R                    []byte                  `protobuf:"bytes,16,opt,name=r,proto3" json:"r,omitempty"`
	S                    []byte                  `protobuf:"bytes,17,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetTransactionType() uint64 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *Transaction) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetAccessList() []*AccessListEntry {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *Transaction) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *Transaction) GetMaxPriorityFeePerGas() []byte {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return nil
}

func (x *Transaction) GetBlobVersionedHashes() [][]byte {
	if x != nil {
		return x.BlobVersionedHashes
	}
	return nil
}

func (x *Transaction) GetMaxFeePerBlobGas() []byte {
	if x != nil {
		return x.MaxFeePerBlobGas
	}
	return nil
}

func (x *Transaction) GetAuthorizationList() []*SetCodeAuthorization {
	if x != nil {
		return x.AuthorizationList
	}
	return nil
}

func (x *Transaction) GetYParity() []byte {
	if x != nil {
		return x.YParity
	}
	return nil
}

func (x *Transaction) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Transaction) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

// Corresponds to bertha_types::AccessListEntry
type AccessListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StorageKeys   [][]byte               `protobuf:"bytes,2,rep,name=storage_keys,json=storageKeys,proto3" json:"storage_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessListEntry) Reset() {
	*x = AccessListEntry{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessListEntry) ProtoMessage() {}

func (x *AccessListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessListEntry.ProtoReflect.Descriptor instead.
func (*AccessListEntry) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *AccessListEntry) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccessListEntry) GetStorageKeys() [][]byte {
	if x != nil {
		return x.StorageKeys
	}
	return nil
}

// Corresponds to bertha_types::SetCodeAuthorization
type SetCodeAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Nonce         uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	YParity       uint64                 `protobuf:"varint,4,opt,name=y_parity,json=yParity,proto3" json:"y_parity,omitempty"`
	R             []byte                 `protobuf:"bytes,5,opt,name=r,proto3" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,6,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCodeAuthorization) Reset() {
	*x = SetCodeAuthorization{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCodeAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCodeAuthorization) ProtoMessage() {}

func (x *SetCodeAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCodeAuthorization.ProtoReflect.Descriptor instead.
func (*SetCodeAuthorization) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *SetCodeAuthorization) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SetCodeAuthorization) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SetCodeAuthorization) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SetCodeAuthorization) GetYParity() uint64 {
	if x != nil {
		return x.YParity
	}
	return 0
}

func (x *SetCodeAuthorization) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SetCodeAuthorization) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

// Corresponds to bertha_types::TransactionReceipt
type TransactionReceipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionType   uint64                 `protobuf:"varint,1,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Status            uint64                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CumulativeGasUsed uint64                 `protobuf:"varint,3,opt,name=cumulative_gas_used,json=cumulativeGasUsed,proto3" json:"cumulative_gas_used,omitempty"`
	Logs              []*Log                 `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionReceipt) Reset() {
	*x = TransactionReceipt{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReceipt) ProtoMessage() {}

func (x *TransactionReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReceipt.ProtoReflect.Descriptor instead.
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionReceipt) GetTransactionType() uint64 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *TransactionReceipt) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TransactionReceipt) GetCumulativeGasUsed() uint64 {
	if x != nil {
		return x.CumulativeGasUsed
	}
	return 0
}

func (x *TransactionReceipt) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Corresponds to bertha_types::Log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Topics        [][]byte               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x05block\"\xdd\x06\n" +
	"\x05Block\x12\x1f\n" +
	"\vparent_hash\x18\x01 \x01(\fR\n" +
	"parentHash\x12\x1f\n" +
	"\vommers_hash\x18\x02 \x01(\fR\n" +
	"ommersHash\x12 \n" +
	"\vbeneficiary\x18\x03 \x01(\fR\vbeneficiary\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x04R\n" +
	"difficulty\x12\x16\n" +
	"\x06number\x18\x06 \x01(\x04R\x06number\x12\x1b\n" +
	"\tgas_limit\x18\a \x01(\x04R\bgasLimit\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\t \x01(\fR\textraData\x12\x1f\n" +
	"\vprev_randao\x18\n" +
	" \x01(\fR\n" +
	"prevRandao\x12\x14\n" +
	"\x05nonce\x18\v \x01(\fR\x05nonce\x126\n" +
	"\ftransactions\x18\f \x03(\v2\x12.block.TransactionR\ftransactions\x125\n" +
	"\breceipts\x18\r \x03(\v2\x19.block.TransactionReceiptR\breceipts\x12,\n" +
	"\x10base_fee_per_gas\x18\x0e \x01(\fH\x00R\rbaseFeePerGas\x88\x01\x01\x12.\n" +
	"\x10withdrawals_root\x18\x0f \x01(\fH\x01R\x0fwithdrawalsRoot\x88\x01\x01\x12'\n" +
	"\rblob_gas_used\x18\x10 \x01(\x04H\x02R\vblobGasUsed\x88\x01\x01\x12+\n" +
	"\x0fexcess_blob_gas\x18\x11 \x01(\x04H\x03R\rexcessBlobGas\x88\x01\x01\x12<\n" +
	"\x18parent_beacon_block_root\x18\x12 \x01(\fH\x04R\x15parentBeaconBlockRoot\x88\x01\x01\x12(\n" +
	"\rrequests_hash\x18\x13 \x01(\fH\x05R\frequestsHash\x88\x01\x01B\x13\n" +
	"\x11_base_fee_per_gasB\x13\n" +
	"\x11_withdrawals_rootB\x10\n" +
	"\x0e_blob_gas_usedB\x12\n" +
	"\x10_excess_blob_gasB\x1b\n" +
	"\x19_parent_beacon_block_rootB\x10\n" +
	"\x0e_requests_hash\"\xe8\x04\n" +
	"\vTransaction\x12)\n" +
	"\x10transaction_type\x18\x01 \x01(\x04R\x0ftransactionType\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\fR\achainId\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x1b\n" +
	"\tgas_price\x18\x04 \x01(\fR\bgasPrice\x12\x1b\n" +
	"\tgas_limit\x18\x05 \x01(\x04R\bgasLimit\x12\x13\n" +
	"\x02to\x18\x06 \x01(\fH\x00R\x02to\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\x127\n" +
	"\vaccess_list\x18\t \x03(\v2\x16.block.AccessListEntryR\n" +
	"accessList\x12%\n" +
	"\x0fmax_fee_per_gas\x18\n" +
	" \x01(\fR\fmaxFeePerGas\x126\n" +
	"\x18max_priority_fee_per_gas\x18\v \x01(\fR\x14maxPriorityFeePerGas\x122\n" +
	"\x15blob_versioned_hashes\x18\f \x03(\fR\x13blobVersionedHashes\x12.\n" +
	"\x14max_fee_per_blob_gas\x18\r \x01(\fR\x10maxFeePerBlobGas\x12J\n" +
	"\x12authorization_list\x18\x0e \x03(\v2\x1b.block.SetCodeAuthorizationR\x11authorizationList\x12\x19\n" +
	"\by_parity\x18\x0f \x01(\fR\ayParity\x12\f\n" +
	"\x01r\x18\x10 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x11 \x01(\fR\x01sB\x05\n" +
	"\x03_to\"N\n" +
	"\x0fAccessListEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12!\n" +
	"\fstorage_keys\x18\x02 \x03(\fR\vstorageKeys\"\x98\x01\n" +
	"\x14SetCodeAuthorization\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x19\n" +
	"\by_parity\x18\x04 \x01(\x04R\ayParity\x12\f\n" +
	"\x01r\x18\x05 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x06 \x01(\fR\x01s\"\xa7\x01\n" +
	"\x12TransactionReceipt\x12)\n" +
	"\x10transaction_type\x18\x01 \x01(\x04R\x0ftransactionType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x04R\x06status\x12.\n" +
	"\x13cumulative_gas_used\x18\x03 \x01(\x04R\x11cumulativeGasUsed\x12\x1e\n" +
	"\x04logs\x18\x04 \x03(\v2\n" +
	".block.LogR\x04logs\"K\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\fR\x06topicsB\vZ\t.;blockdbb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_block_proto_goTypes = []any{
	(*Block)(nil),                // 0: block.Block
	(*Transaction)(nil),          // 1: block.Transaction
	(*AccessListEntry)(nil),      // 2: block.AccessListEntry
	(*SetCodeAuthorization)(nil), // 3: block.SetCodeAuthorization
	(*TransactionReceipt)(nil),   // 4: block.TransactionReceipt
	(*Log)(nil),                  // 5: block.Log
}
var file_block_proto_depIdxs = []int32{
	1, // 0: block.Block.transactions:type_name -> block.Transaction
	4, // 1: block.Block.receipts:type_name -> block.TransactionReceipt
	2, // 2: block.Transaction.access_list:type_name -> block.AccessListEntry
	3, // 3: block.Transaction.authorization_list:type_name -> block.SetCodeAuthorization
	5, // 4: block.TransactionReceipt.logs:type_name -> block.Log
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	file_block_proto_msgTypes[0].OneofWrappers = []any{}
	file_block_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
