// Code generated by MockGen. DO NOT EDIT.
// Source: block_db.go
//
// Generated by this command:
//
//	mockgen -source=block_db.go -destination=block_db_mock.go -package=blockdb
//

// Package blockdb is a generated GoMock package.
package blockdb

import (
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBInterface is a mock of DBInterface interface.
type MockDBInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDBInterfaceMockRecorder
	isgomock struct{}
}

// MockDBInterfaceMockRecorder is the mock recorder for MockDBInterface.
type MockDBInterfaceMockRecorder struct {
	mock *MockDBInterface
}

// NewMockDBInterface creates a new mock instance.
func NewMockDBInterface(ctrl *gomock.Controller) *MockDBInterface {
	mock := &MockDBInterface{ctrl: ctrl}
	mock.recorder = &MockDBInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBInterface) EXPECT() *MockDBInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDBInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBInterface)(nil).Close))
}

// Get mocks base method.
func (m *MockDBInterface) Get(chainID, blockNumber uint64) (*Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", chainID, blockNumber)
	ret0, _ := ret[0].(*Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBInterfaceMockRecorder) Get(chainID, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDBInterface)(nil).Get), chainID, blockNumber)
}

// GetRange mocks base method.
func (m *MockDBInterface) GetRange(chainID, startBlockNumber, endBlockNumber uint64) iter.Seq2[*Block, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRange", chainID, startBlockNumber, endBlockNumber)
	ret0, _ := ret[0].(iter.Seq2[*Block, error])
	return ret0
}

// GetRange indicates an expected call of GetRange.
func (mr *MockDBInterfaceMockRecorder) GetRange(chainID, startBlockNumber, endBlockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRange", reflect.TypeOf((*MockDBInterface)(nil).GetRange), chainID, startBlockNumber, endBlockNumber)
}

// GetRangeRev mocks base method.
func (m *MockDBInterface) GetRangeRev(chainID, startBlockNumber, endBlockNumber uint64) iter.Seq2[*Block, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRangeRev", chainID, startBlockNumber, endBlockNumber)
	ret0, _ := ret[0].(iter.Seq2[*Block, error])
	return ret0
}

// GetRangeRev indicates an expected call of GetRangeRev.
func (mr *MockDBInterfaceMockRecorder) GetRangeRev(chainID, startBlockNumber, endBlockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRangeRev", reflect.TypeOf((*MockDBInterface)(nil).GetRangeRev), chainID, startBlockNumber, endBlockNumber)
}

// Update mocks base method.
func (m *MockDBInterface) Update(chainID uint64, block *Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", chainID, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDBInterfaceMockRecorder) Update(chainID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDBInterface)(nil).Update), chainID, block)
}
