// Copyright 2026 Sonic Operations Ltd
// This file is part of the Sonic Client
//
// Sonic is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Sonic is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Sonic. If not, see <http://www.gnu.org/licenses/>.

// This file is generated by go/test_data_generator/main.go
#![allow(dead_code)]

use crate::{Address, HexConvert, Withdrawal};

#[derive(Debug, Clone)]
pub struct WithdrawalWithTestData {
    pub withdrawal: Withdrawal,
    pub rlp_encoding: Vec<u8>,
    pub json_representation: String,
}

pub fn generate_withdrawals_with_data() -> impl IntoIterator<Item = WithdrawalWithTestData> {
    [
        WithdrawalWithTestData {
            withdrawal: Withdrawal {
                index: 0,
                validator_index: 0,
                address: Address::try_from_hex("0x0000000000000000000000000000000000000000").unwrap(),
                amount: 0,
            },
            rlp_encoding: const_hex::decode("d8808094000000000000000000000000000000000000000080").unwrap(),
            json_representation: r#"{"index":"0x0","validatorIndex":"0x0","address":"0x0000000000000000000000000000000000000000","amount":"0x0"}"#.to_string(),
        },
        WithdrawalWithTestData {
            withdrawal: Withdrawal {
                index: 1,
                validator_index: 1,
                address: Address::try_from_hex("0x0102030405060708090a0B0c0d0e0f1011121314").unwrap(),
                amount: 1,
            },
            rlp_encoding: const_hex::decode("d80101940102030405060708090a0b0c0d0e0f101112131401").unwrap(),
            json_representation: r#"{"index":"0x1","validatorIndex":"0x1","address":"0x0102030405060708090a0b0c0d0e0f1011121314","amount":"0x1"}"#.to_string(),
        },
        WithdrawalWithTestData {
            withdrawal: Withdrawal {
                index: 18446744073709551615,
                validator_index: 18446744073709551615,
                address: Address::try_from_hex("0x0000000000000000000000000000000000000000").unwrap(),
                amount: 18446744073709551615,
            },
            rlp_encoding: const_hex::decode("f088ffffffffffffffff88ffffffffffffffff94000000000000000000000000000000000000000088ffffffffffffffff").unwrap(),
            json_representation: r#"{"index":"0xffffffffffffffff","validatorIndex":"0xffffffffffffffff","address":"0x0000000000000000000000000000000000000000","amount":"0xffffffffffffffff"}"#.to_string(),
        },
        WithdrawalWithTestData {
            withdrawal: Withdrawal {
                index: 18446744073709551614,
                validator_index: 18446744073709551614,
                address: Address::try_from_hex("0x0000000000000000000000000000000000000000").unwrap(),
                amount: 18446744073709551614,
            },
            rlp_encoding: const_hex::decode("f088fffffffffffffffe88fffffffffffffffe94000000000000000000000000000000000000000088fffffffffffffffe").unwrap(),
            json_representation: r#"{"index":"0xfffffffffffffffe","validatorIndex":"0xfffffffffffffffe","address":"0x0000000000000000000000000000000000000000","amount":"0xfffffffffffffffe"}"#.to_string(),
        },
        WithdrawalWithTestData {
            withdrawal: Withdrawal {
                index: 4157513341729910236,
                validator_index: 1947031852228291041,
                address: Address::try_from_hex("0x0000000000000000000000000000000000000000").unwrap(),
                amount: 3388162185735054281,
            },
            rlp_encoding: const_hex::decode("f08839b2745b5ac22ddc881b053f275e7029e1940000000000000000000000000000000000000000882f052b8e822623c9").unwrap(),
            json_representation: r#"{"index":"0x39b2745b5ac22ddc","validatorIndex":"0x1b053f275e7029e1","address":"0x0000000000000000000000000000000000000000","amount":"0x2f052b8e822623c9"}"#.to_string(),
        },
    ]
}
