## The port on which the block service will listen for incoming fetch requests
port = 8080

# [[chains]]
# id = 133337
# name = "Example chain"
# description = "An example blockchain"
# state_updates = ["./state_updates_133337.json"] # optional
