// Code generated by MockGen. DO NOT EDIT.
// Source: metadata.go
//
// Generated by this command:
//
//	mockgen -source=metadata.go -destination=metadata_mock.go -package=replay
//

// Package replay is a generated GoMock package.
package replay

import (
	reflect "reflect"

	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataStore is a mock of MetadataStore interface.
type MockMetadataStore struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStoreMockRecorder
	isgomock struct{}
}

// MockMetadataStoreMockRecorder is the mock recorder for MockMetadataStore.
type MockMetadataStoreMockRecorder struct {
	mock *MockMetadataStore
}

// NewMockMetadataStore creates a new mock instance.
func NewMockMetadataStore(ctrl *gomock.Controller) *MockMetadataStore {
	mock := &MockMetadataStore{ctrl: ctrl}
	mock.recorder = &MockMetadataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStore) EXPECT() *MockMetadataStoreMockRecorder {
	return m.recorder
}

// CommitUpgrades mocks base method.
func (m *MockMetadataStore) CommitUpgrades(blockNumber uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitUpgrades", blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitUpgrades indicates an expected call of CommitUpgrades.
func (mr *MockMetadataStoreMockRecorder) CommitUpgrades(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitUpgrades", reflect.TypeOf((*MockMetadataStore)(nil).CommitUpgrades), blockNumber)
}

// GetCorrectionsAtBlock mocks base method.
func (m *MockMetadataStore) GetCorrectionsAtBlock(blockNumber uint64) map[common.Address]Correction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorrectionsAtBlock", blockNumber)
	ret0, _ := ret[0].(map[common.Address]Correction)
	return ret0
}

// GetCorrectionsAtBlock indicates an expected call of GetCorrectionsAtBlock.
func (mr *MockMetadataStoreMockRecorder) GetCorrectionsAtBlock(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorrectionsAtBlock", reflect.TypeOf((*MockMetadataStore)(nil).GetCorrectionsAtBlock), blockNumber)
}

// GetUpgradeHeights mocks base method.
func (m *MockMetadataStore) GetUpgradeHeights() []opera.UpgradeHeight {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradeHeights")
	ret0, _ := ret[0].([]opera.UpgradeHeight)
	return ret0
}

// GetUpgradeHeights indicates an expected call of GetUpgradeHeights.
func (mr *MockMetadataStoreMockRecorder) GetUpgradeHeights() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradeHeights", reflect.TypeOf((*MockMetadataStore)(nil).GetUpgradeHeights))
}

// GetUpgradesAtBlock mocks base method.
func (m *MockMetadataStore) GetUpgradesAtBlock(blockNumber uint64) opera.Upgrades {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgradesAtBlock", blockNumber)
	ret0, _ := ret[0].(opera.Upgrades)
	return ret0
}

// GetUpgradesAtBlock indicates an expected call of GetUpgradesAtBlock.
func (mr *MockMetadataStoreMockRecorder) GetUpgradesAtBlock(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgradesAtBlock", reflect.TypeOf((*MockMetadataStore)(nil).GetUpgradesAtBlock), blockNumber)
}

// PatchUpgrades mocks base method.
func (m *MockMetadataStore) PatchUpgrades(blockNumber uint64, diff []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchUpgrades", blockNumber, diff)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchUpgrades indicates an expected call of PatchUpgrades.
func (mr *MockMetadataStoreMockRecorder) PatchUpgrades(blockNumber, diff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchUpgrades", reflect.TypeOf((*MockMetadataStore)(nil).PatchUpgrades), blockNumber, diff)
}
