// Code generated by MockGen. DO NOT EDIT.
// Source: metadata.go
//
// Generated by this command:
//
//	mockgen -source=metadata.go -destination=metadata_mock.go -package=replay
//

// Package replay is a generated GoMock package.
package replay

import (
	reflect "reflect"

	opera "github.com/0xsoniclabs/sonic/opera"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataStore is a mock of MetadataStore interface.
type MockMetadataStore struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStoreMockRecorder
	isgomock struct{}
}

// MockMetadataStoreMockRecorder is the mock recorder for MockMetadataStore.
type MockMetadataStoreMockRecorder struct {
	mock *MockMetadataStore
}

// NewMockMetadataStore creates a new mock instance.
func NewMockMetadataStore(ctrl *gomock.Controller) *MockMetadataStore {
	mock := &MockMetadataStore{ctrl: ctrl}
	mock.recorder = &MockMetadataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStore) EXPECT() *MockMetadataStoreMockRecorder {
	return m.recorder
}

// GetCorrections mocks base method.
func (m *MockMetadataStore) GetCorrections(blockNumber uint64) map[common.Address]Correction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorrections", blockNumber)
	ret0, _ := ret[0].(map[common.Address]Correction)
	return ret0
}

// GetCorrections indicates an expected call of GetCorrections.
func (mr *MockMetadataStoreMockRecorder) GetCorrections(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorrections", reflect.TypeOf((*MockMetadataStore)(nil).GetCorrections), blockNumber)
}

// GetRulesAtBlock mocks base method.
func (m *MockMetadataStore) GetRulesAtBlock(blockNumber uint64) opera.Rules {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesAtBlock", blockNumber)
	ret0, _ := ret[0].(opera.Rules)
	return ret0
}

// GetRulesAtBlock indicates an expected call of GetRulesAtBlock.
func (mr *MockMetadataStoreMockRecorder) GetRulesAtBlock(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesAtBlock", reflect.TypeOf((*MockMetadataStore)(nil).GetRulesAtBlock), blockNumber)
}

// GetUpgrades mocks base method.
func (m *MockMetadataStore) GetUpgrades() []opera.UpgradeHeight {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpgrades")
	ret0, _ := ret[0].([]opera.UpgradeHeight)
	return ret0
}

// GetUpgrades indicates an expected call of GetUpgrades.
func (mr *MockMetadataStoreMockRecorder) GetUpgrades() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpgrades", reflect.TypeOf((*MockMetadataStore)(nil).GetUpgrades))
}

// StoreUpgrade mocks base method.
func (m *MockMetadataStore) StoreUpgrade(upgrade opera.UpgradeHeight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreUpgrade", upgrade)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreUpgrade indicates an expected call of StoreUpgrade.
func (mr *MockMetadataStoreMockRecorder) StoreUpgrade(upgrade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreUpgrade", reflect.TypeOf((*MockMetadataStore)(nil).StoreUpgrade), upgrade)
}
