// Code generated by MockGen. DO NOT EDIT.
// Source: replay.go
//
// Generated by this command:
//
//	mockgen -source=replay.go -destination=replay_mock.go -package=replay
//

// Package replay is a generated GoMock package.
package replay

import (
	reflect "reflect"

	future "github.com/0xsoniclabs/carmen/go/common/future"
	result "github.com/0xsoniclabs/carmen/go/common/result"
	opera "github.com/0xsoniclabs/sonic/opera"
	tosca "github.com/0xsoniclabs/tosca/go/tosca"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	params "github.com/ethereum/go-ethereum/params"
	gomock "go.uber.org/mock/gomock"
)

// MockChain is a mock of Chain interface.
type MockChain struct {
	ctrl     *gomock.Controller
	recorder *MockChainMockRecorder
	isgomock struct{}
}

// MockChainMockRecorder is the mock recorder for MockChain.
type MockChainMockRecorder struct {
	mock *MockChain
}

// NewMockChain creates a new mock instance.
func NewMockChain(ctrl *gomock.Controller) *MockChain {
	mock := &MockChain{ctrl: ctrl}
	mock.recorder = &MockChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChain) EXPECT() *MockChainMockRecorder {
	return m.recorder
}

// ApplyBlock mocks base method.
func (m *MockChain) ApplyBlock(arg0 *types.Block) (types.Receipts, future.Future[result.Result[common.Hash]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBlock", arg0)
	ret0, _ := ret[0].(types.Receipts)
	ret1, _ := ret[1].(future.Future[result.Result[common.Hash]])
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ApplyBlock indicates an expected call of ApplyBlock.
func (mr *MockChainMockRecorder) ApplyBlock(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBlock", reflect.TypeOf((*MockChain)(nil).ApplyBlock), arg0)
}

// ChainID mocks base method.
func (m *MockChain) ChainID() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ChainID indicates an expected call of ChainID.
func (mr *MockChainMockRecorder) ChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockChain)(nil).ChainID))
}

// CloneBlockHashHistory mocks base method.
func (m *MockChain) CloneBlockHashHistory() *blockHashHistory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneBlockHashHistory")
	ret0, _ := ret[0].(*blockHashHistory)
	return ret0
}

// CloneBlockHashHistory indicates an expected call of CloneBlockHashHistory.
func (mr *MockChainMockRecorder) CloneBlockHashHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneBlockHashHistory", reflect.TypeOf((*MockChain)(nil).CloneBlockHashHistory))
}

// GetBlockHash mocks base method.
func (m *MockChain) GetBlockHash(blockNumber uint64) common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockHash", blockNumber)
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// GetBlockHash indicates an expected call of GetBlockHash.
func (mr *MockChainMockRecorder) GetBlockHash(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHash", reflect.TypeOf((*MockChain)(nil).GetBlockHash), blockNumber)
}

// IsMptConformant mocks base method.
func (m *MockChain) IsMptConformant() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMptConformant")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMptConformant indicates an expected call of IsMptConformant.
func (mr *MockChainMockRecorder) IsMptConformant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMptConformant", reflect.TypeOf((*MockChain)(nil).IsMptConformant))
}

// IsVerkleConformant mocks base method.
func (m *MockChain) IsVerkleConformant() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVerkleConformant")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsVerkleConformant indicates an expected call of IsVerkleConformant.
func (mr *MockChainMockRecorder) IsVerkleConformant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVerkleConformant", reflect.TypeOf((*MockChain)(nil).IsVerkleConformant))
}

// MaybeSnapshot mocks base method.
func (m *MockChain) MaybeSnapshot(blockNumber uint64, stateRoot future.Future[result.Result[common.Hash]]) (future.Future[result.Result[common.Hash]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaybeSnapshot", blockNumber, stateRoot)
	ret0, _ := ret[0].(future.Future[result.Result[common.Hash]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MaybeSnapshot indicates an expected call of MaybeSnapshot.
func (mr *MockChainMockRecorder) MaybeSnapshot(blockNumber, stateRoot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaybeSnapshot", reflect.TypeOf((*MockChain)(nil).MaybeSnapshot), blockNumber, stateRoot)
}

// MockArchiveState is a mock of ArchiveState interface.
type MockArchiveState struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveStateMockRecorder
	isgomock struct{}
}

// MockArchiveStateMockRecorder is the mock recorder for MockArchiveState.
type MockArchiveStateMockRecorder struct {
	mock *MockArchiveState
}

// NewMockArchiveState creates a new mock instance.
func NewMockArchiveState(ctrl *gomock.Controller) *MockArchiveState {
	mock := &MockArchiveState{ctrl: ctrl}
	mock.recorder = &MockArchiveStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveState) EXPECT() *MockArchiveStateMockRecorder {
	return m.recorder
}

// ApplyArchiveBlock mocks base method.
func (m *MockArchiveState) ApplyArchiveBlock(block *types.Block, interpreter tosca.Interpreter, processor Processor, upgrades opera.Upgrades, corrections map[common.Address]Correction, chainConfig *params.ChainConfig) (types.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyArchiveBlock", block, interpreter, processor, upgrades, corrections, chainConfig)
	ret0, _ := ret[0].(types.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyArchiveBlock indicates an expected call of ApplyArchiveBlock.
func (mr *MockArchiveStateMockRecorder) ApplyArchiveBlock(block, interpreter, processor, upgrades, corrections, chainConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyArchiveBlock", reflect.TypeOf((*MockArchiveState)(nil).ApplyArchiveBlock), block, interpreter, processor, upgrades, corrections, chainConfig)
}

// GetArchiveBlockHeight mocks base method.
func (m *MockArchiveState) GetArchiveBlockHeight() (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveBlockHeight")
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchiveBlockHeight indicates an expected call of GetArchiveBlockHeight.
func (mr *MockArchiveStateMockRecorder) GetArchiveBlockHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveBlockHeight", reflect.TypeOf((*MockArchiveState)(nil).GetArchiveBlockHeight))
}

// MockStateFlusher is a mock of StateFlusher interface.
type MockStateFlusher struct {
	ctrl     *gomock.Controller
	recorder *MockStateFlusherMockRecorder
	isgomock struct{}
}

// MockStateFlusherMockRecorder is the mock recorder for MockStateFlusher.
type MockStateFlusherMockRecorder struct {
	mock *MockStateFlusher
}

// NewMockStateFlusher creates a new mock instance.
func NewMockStateFlusher(ctrl *gomock.Controller) *MockStateFlusher {
	mock := &MockStateFlusher{ctrl: ctrl}
	mock.recorder = &MockStateFlusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateFlusher) EXPECT() *MockStateFlusherMockRecorder {
	return m.recorder
}

// FlushState mocks base method.
func (m *MockStateFlusher) FlushState() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushState")
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushState indicates an expected call of FlushState.
func (mr *MockStateFlusherMockRecorder) FlushState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushState", reflect.TypeOf((*MockStateFlusher)(nil).FlushState))
}
