// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source=state.go -destination=state_mock.go -package=replay
//

// Package replay is a generated GoMock package.
package replay

import (
	big "math/big"
	reflect "reflect"

	evmcore "github.com/0xsoniclabs/sonic/evmcore"
	core_types "github.com/0xsoniclabs/sonic/evmcore/core_types"
	state "github.com/0xsoniclabs/sonic/inter/state"
	vm "github.com/ethereum/go-ethereum/core/vm"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// ProcessWithDifficulty mocks base method.
func (m *MockProcessor) ProcessWithDifficulty(block *evmcore.EvmBlock, statedb state.StateDB, cfg vm.Config, gasLimit uint64, usedGas *uint64, trueTxOffset int, onNewLog func(*core_types.Log), difficulty *big.Int, remainingSize uint64) evmcore.ProcessSummary {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWithDifficulty", block, statedb, cfg, gasLimit, usedGas, trueTxOffset, onNewLog, difficulty, remainingSize)
	ret0, _ := ret[0].(evmcore.ProcessSummary)
	return ret0
}

// ProcessWithDifficulty indicates an expected call of ProcessWithDifficulty.
func (mr *MockProcessorMockRecorder) ProcessWithDifficulty(block, statedb, cfg, gasLimit, usedGas, trueTxOffset, onNewLog, difficulty, remainingSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWithDifficulty", reflect.TypeOf((*MockProcessor)(nil).ProcessWithDifficulty), block, statedb, cfg, gasLimit, usedGas, trueTxOffset, onNewLog, difficulty, remainingSize)
}
