// Code generated by MockGen. DO NOT EDIT.
// Source: progress_indicator.go
//
// Generated by this command:
//
//	mockgen -source=progress_indicator.go -destination=progress_indicator_mock.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProgressIndicator is a mock of ProgressIndicator interface.
type MockProgressIndicator struct {
	ctrl     *gomock.Controller
	recorder *MockProgressIndicatorMockRecorder
	isgomock struct{}
}

// MockProgressIndicatorMockRecorder is the mock recorder for MockProgressIndicator.
type MockProgressIndicatorMockRecorder struct {
	mock *MockProgressIndicator
}

// NewMockProgressIndicator creates a new mock instance.
func NewMockProgressIndicator(ctrl *gomock.Controller) *MockProgressIndicator {
	mock := &MockProgressIndicator{ctrl: ctrl}
	mock.recorder = &MockProgressIndicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressIndicator) EXPECT() *MockProgressIndicatorMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockProgressIndicator) Add(num int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", num)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockProgressIndicatorMockRecorder) Add(num any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockProgressIndicator)(nil).Add), num)
}

// MockProgressIndicatorFactory is a mock of ProgressIndicatorFactory interface.
type MockProgressIndicatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProgressIndicatorFactoryMockRecorder
	isgomock struct{}
}

// MockProgressIndicatorFactoryMockRecorder is the mock recorder for MockProgressIndicatorFactory.
type MockProgressIndicatorFactoryMockRecorder struct {
	mock *MockProgressIndicatorFactory
}

// NewMockProgressIndicatorFactory creates a new mock instance.
func NewMockProgressIndicatorFactory(ctrl *gomock.Controller) *MockProgressIndicatorFactory {
	mock := &MockProgressIndicatorFactory{ctrl: ctrl}
	mock.recorder = &MockProgressIndicatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressIndicatorFactory) EXPECT() *MockProgressIndicatorFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockProgressIndicatorFactory) New(max int64, description ...string) ProgressIndicator {
	m.ctrl.T.Helper()
	varargs := []any{max}
	for _, a := range description {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(ProgressIndicator)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockProgressIndicatorFactoryMockRecorder) New(max any, description ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{max}, description...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProgressIndicatorFactory)(nil).New), varargs...)
}
