// Code generated by MockGen. DO NOT EDIT.
// Source: block_db.go
//
// Generated by this command:
//
//	mockgen -source=block_db.go -destination=block_db_mock.go -package=blockdb
//

// Package blockdb is a generated GoMock package.
package blockdb

import (
	iter "iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlockDB is a mock of BlockDB interface.
type MockBlockDB struct {
	ctrl     *gomock.Controller
	recorder *MockBlockDBMockRecorder
	isgomock struct{}
}

// MockBlockDBMockRecorder is the mock recorder for MockBlockDB.
type MockBlockDBMockRecorder struct {
	mock *MockBlockDB
}

// NewMockBlockDB creates a new mock instance.
func NewMockBlockDB(ctrl *gomock.Controller) *MockBlockDB {
	mock := &MockBlockDB{ctrl: ctrl}
	mock.recorder = &MockBlockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockDB) EXPECT() *MockBlockDBMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBlockDB) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBlockDBMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBlockDB)(nil).Close))
}

// Get mocks base method.
func (m *MockBlockDB) Get(chainID, blockNumber uint64) (*Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", chainID, blockNumber)
	ret0, _ := ret[0].(*Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBlockDBMockRecorder) Get(chainID, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBlockDB)(nil).Get), chainID, blockNumber)
}

// GetRange mocks base method.
func (m *MockBlockDB) GetRange(chainID, startBlockNumber, endBlockNumber uint64) iter.Seq2[*Block, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRange", chainID, startBlockNumber, endBlockNumber)
	ret0, _ := ret[0].(iter.Seq2[*Block, error])
	return ret0
}

// GetRange indicates an expected call of GetRange.
func (mr *MockBlockDBMockRecorder) GetRange(chainID, startBlockNumber, endBlockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRange", reflect.TypeOf((*MockBlockDB)(nil).GetRange), chainID, startBlockNumber, endBlockNumber)
}

// GetRangeRev mocks base method.
func (m *MockBlockDB) GetRangeRev(chainID, startBlockNumber, endBlockNumber uint64) iter.Seq2[*Block, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRangeRev", chainID, startBlockNumber, endBlockNumber)
	ret0, _ := ret[0].(iter.Seq2[*Block, error])
	return ret0
}

// GetRangeRev indicates an expected call of GetRangeRev.
func (mr *MockBlockDBMockRecorder) GetRangeRev(chainID, startBlockNumber, endBlockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRangeRev", reflect.TypeOf((*MockBlockDB)(nil).GetRangeRev), chainID, startBlockNumber, endBlockNumber)
}

// Update mocks base method.
func (m *MockBlockDB) Update(chainID uint64, block *Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", chainID, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBlockDBMockRecorder) Update(chainID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlockDB)(nil).Update), chainID, block)
}
