// Code generated by MockGen. DO NOT EDIT.
// Source: diagnostics.go
//
// Generated by this command:
//
//	mockgen -source=diagnostics.go -destination=diagnostics_mock.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mock_infoLogger is a mock of _infoLogger interface.
type Mock_infoLogger struct {
	ctrl     *gomock.Controller
	recorder *Mock_infoLoggerMockRecorder
	isgomock struct{}
}

// Mock_infoLoggerMockRecorder is the mock recorder for Mock_infoLogger.
type Mock_infoLoggerMockRecorder struct {
	mock *Mock_infoLogger
}

// NewMock_infoLogger creates a new mock instance.
func NewMock_infoLogger(ctrl *gomock.Controller) *Mock_infoLogger {
	mock := &Mock_infoLogger{ctrl: ctrl}
	mock.recorder = &Mock_infoLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_infoLogger) EXPECT() *Mock_infoLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *Mock_infoLogger) Error(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *Mock_infoLoggerMockRecorder) Error(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mock_infoLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *Mock_infoLogger) Info(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *Mock_infoLoggerMockRecorder) Info(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*Mock_infoLogger)(nil).Info), varargs...)
}
