// Code generated by MockGen. DO NOT EDIT.
// Source: replay.go
//
// Generated by this command:
//
//	mockgen -source=replay.go -destination=replay_mock.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	future "github.com/0xsoniclabs/carmen/go/common/future"
	result "github.com/0xsoniclabs/carmen/go/common/result"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockChain is a mock of Chain interface.
type MockChain struct {
	ctrl     *gomock.Controller
	recorder *MockChainMockRecorder
	isgomock struct{}
}

// MockChainMockRecorder is the mock recorder for MockChain.
type MockChainMockRecorder struct {
	mock *MockChain
}

// NewMockChain creates a new mock instance.
func NewMockChain(ctrl *gomock.Controller) *MockChain {
	mock := &MockChain{ctrl: ctrl}
	mock.recorder = &MockChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChain) EXPECT() *MockChainMockRecorder {
	return m.recorder
}

// ApplyBlock mocks base method.
func (m *MockChain) ApplyBlock(arg0 *types.Block, arg1 Metadata) (types.Receipts, future.Future[result.Result[common.Hash]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyBlock", arg0, arg1)
	ret0, _ := ret[0].(types.Receipts)
	ret1, _ := ret[1].(future.Future[result.Result[common.Hash]])
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ApplyBlock indicates an expected call of ApplyBlock.
func (mr *MockChainMockRecorder) ApplyBlock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyBlock", reflect.TypeOf((*MockChain)(nil).ApplyBlock), arg0, arg1)
}

// ChainID mocks base method.
func (m *MockChain) ChainID() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// ChainID indicates an expected call of ChainID.
func (mr *MockChainMockRecorder) ChainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockChain)(nil).ChainID))
}

// IsMptConformant mocks base method.
func (m *MockChain) IsMptConformant() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMptConformant")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMptConformant indicates an expected call of IsMptConformant.
func (mr *MockChainMockRecorder) IsMptConformant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMptConformant", reflect.TypeOf((*MockChain)(nil).IsMptConformant))
}

// IsVerkleConformant mocks base method.
func (m *MockChain) IsVerkleConformant() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVerkleConformant")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsVerkleConformant indicates an expected call of IsVerkleConformant.
func (mr *MockChainMockRecorder) IsVerkleConformant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVerkleConformant", reflect.TypeOf((*MockChain)(nil).IsVerkleConformant))
}
