# Copyright 2026 Sonic Operations Ltd
# This file is part of the Sonic Client
#
# Sonic is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Sonic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Sonic. If not, see <http://www.gnu.org/licenses/>.

name: Go

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install rocksdb
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev
    - name: golangci-lint go tools
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12.2
        working-directory: go
    - name: golangci-lint test_data_generator
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12.2
        working-directory: utils/test_data_generator

  license-check:
    name: license check
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: utils/scripts/license/go.sum
    - name: check license headers
      run: go run ./utils/scripts/license/add_license_header.go -dir ./ -check

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install rocksdb
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev
    - name: go test
      working-directory: go
      run: go test --count 1 ./...

  protobuf:
    name: protobuf
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install rocksdb, protobuf compiler
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev protobuf-compiler
    - name: install protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - name: regenerate protobuf definitions
      working-directory: go
      run: go generate blockdb/proto_gen.go
    # The goal is to ensure that the protobuf definitions and the generated
    # Go code are not out of sync. Because the exact output may depend on the
    # version of the protobuf compiler, we do not check for exact equality of
    # the generated go code, but just make sure that the code still compiles.
    - name: go build
      working-directory: go
      run: go build ./...

  # This is currently disabled because we can not guarantee that the protobuf compiler versions between CI and dev machines do not get out of sync.
  #codegen:
    #name: codegen
    #runs-on: ubuntu-latest

    #steps:
    #- name: checkout
      #uses: actions/checkout@v4
    #- name: setup go
      #uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      #with:
        #go-version: "1.26.0"
    #- name: install deps
      #run: |
        #sudo apt-get install protobuf-compiler
        #go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    #- name: go generate
      #working-directory: go
      #run: |
        #export PATH="${PATH}:$(go env GOPATH)/bin"
        #go generate .
        #git diff --exit-code # make sure there are no changes after code generation
