# Copyright 2026 Sonic Operations Ltd
# This file is part of the Sonic Client
#
# Sonic is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Sonic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Sonic. If not, see <http://www.gnu.org/licenses/>.

name: Go

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/go.yaml'
      - 'go/**'
      - 'utils/test_data_generator/**'
  pull_request:
    branches: [ "**" ]
    paths:
      - '.github/workflows/go.yaml'
      - 'go/**'
      - 'utils/test_data_generator/**'
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install rocksdb
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev
    - name: install golangci-lint
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
    - name: golangci go tools
      working-directory: go
      run: |
        export PATH="${PATH}:$(go env GOPATH)/bin"
        golangci-lint run ./...
    - name: golanci test_data_generator
      working-directory: utils/test_data_generator
      run: |
        export PATH="${PATH}:$(go env GOPATH)/bin"
        golangci-lint run ./...

  license-check:
    name: license check
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: utils/scripts/license/go.sum
    - name: check license headers
      run: go run ./utils/scripts/license/add_license_header.go -dir ./ -check

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install rocksdb
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev
    - name: go test
      working-directory: go
      run: go test --count 1 ./...

  carmen-tracy-patch:
    name: carmen-tracy-patches
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        path: bertha
    - name: clone Carmen
      run: git clone --depth 1 https://github.com/0xsoniclabs/carmen
    - name: clone Tracy
      run: git clone --depth 1 https://github.com/0xsoniclabs/tracy
    - name: check if carmen and tracy patches apply
      working-directory: bertha/go
      run: git apply enable-carmen.patch && git apply enable-tracy.patch
    - name: check if go module is tidy
      working-directory: bertha/go
      run: go build -n ./...

  # This is currently disabled because we can not guarantee that the protobuf compiler versions between CI and dev machines do not get out of sync.
  #codegen:
    #name: codegen
    #runs-on: ubuntu-latest

    #steps:
    #- name: checkout
      #uses: actions/checkout@v4
    #- name: setup go
      #uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      #with:
        #go-version: "1.26.0"
    #- name: install deps
      #run: |
        #sudo apt-get install protobuf-compiler
        #go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    #- name: go generate
      #working-directory: go
      #run: |
        #export PATH="${PATH}:$(go env GOPATH)/bin"
        #go generate .
        #git diff --exit-code # make sure there are no changes after code generation
