# Copyright 2026 Sonic Operations Ltd
# This file is part of the Bertha testing infrastructure for Sonic.
#
# Bertha is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bertha is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Bertha. If not, see <http://www.gnu.org/licenses/>.

name: Integration

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  import-verify-replay:
    name: import-verify-replay
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: go/go.sum
    - name: install protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install rocksdb
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: librocksdb-dev
    - name: load cache
      uses: Swatinem/rust-cache@v2
    - name: init blockdb
      run: cargo run -- init
    - name: import g-file
      run: cargo run -- import-gfile data/genesis/small.g
    - name: verify blockdb (Rust)
      run: cargo run -- verify 4003
    - name: verify blockdb (Go)
      working-directory: go
      run: go run . verify --database-dir ../.blockdb --chain-id 4003
    - name: replay blocks
      working-directory: go
      run: go run . replay --database-dir ../.blockdb --json-genesis ../data/genesis/small.json

  generate-test-data:
    name: generate-test-data
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: install rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: setup go
      uses: actions/setup-go@v5 # Use actions/setup-go to specify the Go version
      with:
        go-version: "1.26.0"
        cache-dependency-path: utils/test_data_generator/go.sum
    - name: generate test data
      working-directory: utils/test_data_generator
      run: |
        go run . transactions > ../../bertha-types/src/test_data/test_data_transaction.rs &&
        go run . receipts > ../../bertha-types/src/test_data/test_data_receipts.rs &&
        go run . withdrawals > ../../bertha-types/src/test_data/test_data_withdrawals.rs &&
        go run . blocks > ../../bertha-types/src/test_data/test_data_blocks.rs &&
        git diff --exit-code # make sure there are no changes after test data generation

  carmen-tracy-patch:
    name: carmen-tracy-patches
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        path: bertha
    - name: clone Carmen
      run: git clone --depth 1 https://github.com/0xsoniclabs/carmen
    - name: clone Tracy
      run: git clone --depth 1 https://github.com/0xsoniclabs/tracy
    - name: check if carmen and tracy patches apply
      working-directory: bertha/go
      run: git apply enable-carmen.patch && git apply enable-tracy.patch
    - name: check if go module is tidy
      working-directory: bertha/go
      run: go build -n ./...
